package dao;
// Generated 20 janv. 2017 05:45:27 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Contrat generated by hbm2java
 */
public class Contrat  implements java.io.Serializable {


     private Integer idContrat;
     private Client client;
     private Voiture voiture;
     private int idAgent;
     private Date dateContrat;
     private int nbrJourLoc;

    public Contrat() {
    }

    public Contrat(Client client, Voiture voiture, int idAgent, Date dateContrat, int nbrJourLoc) {
       this.client = client;
       this.voiture = voiture;
       this.idAgent = idAgent;
       this.dateContrat = dateContrat;
       this.nbrJourLoc = nbrJourLoc;
    }
   
    public Integer getIdContrat() {
        return this.idContrat;
    }
    
    public void setIdContrat(Integer idContrat) {
        this.idContrat = idContrat;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Voiture getVoiture() {
        return this.voiture;
    }
    
    public void setVoiture(Voiture voiture) {
        this.voiture = voiture;
    }
    public int getIdAgent() {
        return this.idAgent;
    }
    
    public void setIdAgent(int idAgent) {
        this.idAgent = idAgent;
    }
    public Date getDateContrat() {
        return this.dateContrat;
    }
    
    public void setDateContrat(Date dateContrat) {
        this.dateContrat = dateContrat;
    }
    public int getNbrJourLoc() {
        return this.nbrJourLoc;
    }
    
    public void setNbrJourLoc(int nbrJourLoc) {
        this.nbrJourLoc = nbrJourLoc;
    }




}


