package dao;
// Generated 20 janv. 2017 05:45:27 by Hibernate Tools 4.3.1



/**
 * Facture generated by hbm2java
 */
public class Facture  implements java.io.Serializable {


     private Integer idFac;
     private Client client;
     private Voiture voiture;
     private String numCarteCl;
     private int dateFac;
     private int montantFac;

    public Facture() {
    }

    public Facture(Client client, Voiture voiture, String numCarteCl, int dateFac, int montantFac) {
       this.client = client;
       this.voiture = voiture;
       this.numCarteCl = numCarteCl;
       this.dateFac = dateFac;
       this.montantFac = montantFac;
    }
   
    public Integer getIdFac() {
        return this.idFac;
    }
    
    public void setIdFac(Integer idFac) {
        this.idFac = idFac;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Voiture getVoiture() {
        return this.voiture;
    }
    
    public void setVoiture(Voiture voiture) {
        this.voiture = voiture;
    }
    public String getNumCarteCl() {
        return this.numCarteCl;
    }
    
    public void setNumCarteCl(String numCarteCl) {
        this.numCarteCl = numCarteCl;
    }
    public int getDateFac() {
        return this.dateFac;
    }
    
    public void setDateFac(int dateFac) {
        this.dateFac = dateFac;
    }
    public int getMontantFac() {
        return this.montantFac;
    }
    
    public void setMontantFac(int montantFac) {
        this.montantFac = montantFac;
    }




}


