package dao;
// Generated 20 janv. 2017 05:45:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Parc generated by hbm2java
 */
public class Parc  implements java.io.Serializable {


     private Integer idPac;
     private String numParc;
     private String categorieVoiture;
     private Set voitures = new HashSet(0);

    public Parc() {
    }

	
    public Parc(String numParc, String categorieVoiture) {
        this.numParc = numParc;
        this.categorieVoiture = categorieVoiture;
    }
    public Parc(String numParc, String categorieVoiture, Set voitures) {
       this.numParc = numParc;
       this.categorieVoiture = categorieVoiture;
       this.voitures = voitures;
    }
   
    public Integer getIdPac() {
        return this.idPac;
    }
    
    public void setIdPac(Integer idPac) {
        this.idPac = idPac;
    }
    public String getNumParc() {
        return this.numParc;
    }
    
    public void setNumParc(String numParc) {
        this.numParc = numParc;
    }
    public String getCategorieVoiture() {
        return this.categorieVoiture;
    }
    
    public void setCategorieVoiture(String categorieVoiture) {
        this.categorieVoiture = categorieVoiture;
    }
    public Set getVoitures() {
        return this.voitures;
    }
    
    public void setVoitures(Set voitures) {
        this.voitures = voitures;
    }




}


