package dao;
// Generated 20 janv. 2017 05:45:27 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private Integer idReserv;
     private Client client;
     private Voiture voiture;
     private Date dateDebutReserv;
     private Date dateFinReserv;
     private String etatReserve;

    public Reservation() {
    }

    public Reservation(Client client, Voiture voiture, Date dateDebutReserv, Date dateFinReserv, String etatReserve) {
       this.client = client;
       this.voiture = voiture;
       this.dateDebutReserv = dateDebutReserv;
       this.dateFinReserv = dateFinReserv;
       this.etatReserve = etatReserve;
    }
   
    public Integer getIdReserv() {
        return this.idReserv;
    }
    
    public void setIdReserv(Integer idReserv) {
        this.idReserv = idReserv;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Voiture getVoiture() {
        return this.voiture;
    }
    
    public void setVoiture(Voiture voiture) {
        this.voiture = voiture;
    }
    public Date getDateDebutReserv() {
        return this.dateDebutReserv;
    }
    
    public void setDateDebutReserv(Date dateDebutReserv) {
        this.dateDebutReserv = dateDebutReserv;
    }
    public Date getDateFinReserv() {
        return this.dateFinReserv;
    }
    
    public void setDateFinReserv(Date dateFinReserv) {
        this.dateFinReserv = dateFinReserv;
    }
    public String getEtatReserve() {
        return this.etatReserve;
    }
    
    public void setEtatReserve(String etatReserve) {
        this.etatReserve = etatReserve;
    }




}


