package dao;
// Generated 20 janv. 2017 05:45:27 by Hibernate Tools 4.3.1



/**
 * TcPays generated by hbm2java
 */
public class TcPays  implements java.io.Serializable {


     private String sortOrder;
     private String commoName;
     private String formalName;
     private String type;
     private String subType;
     private String sovereignty;
     private String capital;
     private String iso4217CurrencyCode;
     private String iso4217CurrencyName;
     private String ituTTelephoneCode;
     private String iso316612LetterCode;
     private String iso316613LetterCode;
     private String iso31661Number;
     private String ianaCountryCodeTld;

    public TcPays() {
    }

	
    public TcPays(String sortOrder) {
        this.sortOrder = sortOrder;
    }
    public TcPays(String sortOrder, String commoName, String formalName, String type, String subType, String sovereignty, String capital, String iso4217CurrencyCode, String iso4217CurrencyName, String ituTTelephoneCode, String iso316612LetterCode, String iso316613LetterCode, String iso31661Number, String ianaCountryCodeTld) {
       this.sortOrder = sortOrder;
       this.commoName = commoName;
       this.formalName = formalName;
       this.type = type;
       this.subType = subType;
       this.sovereignty = sovereignty;
       this.capital = capital;
       this.iso4217CurrencyCode = iso4217CurrencyCode;
       this.iso4217CurrencyName = iso4217CurrencyName;
       this.ituTTelephoneCode = ituTTelephoneCode;
       this.iso316612LetterCode = iso316612LetterCode;
       this.iso316613LetterCode = iso316613LetterCode;
       this.iso31661Number = iso31661Number;
       this.ianaCountryCodeTld = ianaCountryCodeTld;
    }
   
    public String getSortOrder() {
        return this.sortOrder;
    }
    
    public void setSortOrder(String sortOrder) {
        this.sortOrder = sortOrder;
    }
    public String getCommoName() {
        return this.commoName;
    }
    
    public void setCommoName(String commoName) {
        this.commoName = commoName;
    }
    public String getFormalName() {
        return this.formalName;
    }
    
    public void setFormalName(String formalName) {
        this.formalName = formalName;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getSubType() {
        return this.subType;
    }
    
    public void setSubType(String subType) {
        this.subType = subType;
    }
    public String getSovereignty() {
        return this.sovereignty;
    }
    
    public void setSovereignty(String sovereignty) {
        this.sovereignty = sovereignty;
    }
    public String getCapital() {
        return this.capital;
    }
    
    public void setCapital(String capital) {
        this.capital = capital;
    }
    public String getIso4217CurrencyCode() {
        return this.iso4217CurrencyCode;
    }
    
    public void setIso4217CurrencyCode(String iso4217CurrencyCode) {
        this.iso4217CurrencyCode = iso4217CurrencyCode;
    }
    public String getIso4217CurrencyName() {
        return this.iso4217CurrencyName;
    }
    
    public void setIso4217CurrencyName(String iso4217CurrencyName) {
        this.iso4217CurrencyName = iso4217CurrencyName;
    }
    public String getItuTTelephoneCode() {
        return this.ituTTelephoneCode;
    }
    
    public void setItuTTelephoneCode(String ituTTelephoneCode) {
        this.ituTTelephoneCode = ituTTelephoneCode;
    }
    public String getIso316612LetterCode() {
        return this.iso316612LetterCode;
    }
    
    public void setIso316612LetterCode(String iso316612LetterCode) {
        this.iso316612LetterCode = iso316612LetterCode;
    }
    public String getIso316613LetterCode() {
        return this.iso316613LetterCode;
    }
    
    public void setIso316613LetterCode(String iso316613LetterCode) {
        this.iso316613LetterCode = iso316613LetterCode;
    }
    public String getIso31661Number() {
        return this.iso31661Number;
    }
    
    public void setIso31661Number(String iso31661Number) {
        this.iso31661Number = iso31661Number;
    }
    public String getIanaCountryCodeTld() {
        return this.ianaCountryCodeTld;
    }
    
    public void setIanaCountryCodeTld(String ianaCountryCodeTld) {
        this.ianaCountryCodeTld = ianaCountryCodeTld;
    }




}


