package dao;
// Generated 20 janv. 2017 05:45:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Voiture generated by hbm2java
 */
public class Voiture  implements java.io.Serializable {


     private Integer idVoiture;
     private Parc parc;
     private String immatriculationVoiture;
     private String marqueVoiture;
     private String modeleVoiture;
     private String categorieVoiture;
     private String couleurVoiture;
     private String carburantVoiture;
     private String boiteVitesseVoiture;
     private String climatisationVoiture;
     private int nbrPortesVoiture;
     private int nbrPlacesVoiture;
     private String typeVoiture;
     private String etatVoiture;
     private String anneeMiseService;
     private String type;
     private byte[] image;
     private String prixParJour3jour;
     private String prixParJour1semaine;
     private Set entretients = new HashSet(0);
     private Set factures = new HashSet(0);
     private Set contrats = new HashSet(0);
     private Set reservations = new HashSet(0);

    public Voiture() {
    }

	
    public Voiture(Parc parc, String immatriculationVoiture, String marqueVoiture, String modeleVoiture, String categorieVoiture, String couleurVoiture, String carburantVoiture, String boiteVitesseVoiture, String climatisationVoiture, int nbrPortesVoiture, int nbrPlacesVoiture, String typeVoiture, String etatVoiture, String anneeMiseService, String type, byte[] image, String prixParJour3jour, String prixParJour1semaine) {
        this.parc = parc;
        this.immatriculationVoiture = immatriculationVoiture;
        this.marqueVoiture = marqueVoiture;
        this.modeleVoiture = modeleVoiture;
        this.categorieVoiture = categorieVoiture;
        this.couleurVoiture = couleurVoiture;
        this.carburantVoiture = carburantVoiture;
        this.boiteVitesseVoiture = boiteVitesseVoiture;
        this.climatisationVoiture = climatisationVoiture;
        this.nbrPortesVoiture = nbrPortesVoiture;
        this.nbrPlacesVoiture = nbrPlacesVoiture;
        this.typeVoiture = typeVoiture;
        this.etatVoiture = etatVoiture;
        this.anneeMiseService = anneeMiseService;
        this.type = type;
        this.image = image;
        this.prixParJour3jour = prixParJour3jour;
        this.prixParJour1semaine = prixParJour1semaine;
    }
    public Voiture(Parc parc, String immatriculationVoiture, String marqueVoiture, String modeleVoiture, String categorieVoiture, String couleurVoiture, String carburantVoiture, String boiteVitesseVoiture, String climatisationVoiture, int nbrPortesVoiture, int nbrPlacesVoiture, String typeVoiture, String etatVoiture, String anneeMiseService, String type, byte[] image, String prixParJour3jour, String prixParJour1semaine, Set entretients, Set factures, Set contrats, Set reservations) {
       this.parc = parc;
       this.immatriculationVoiture = immatriculationVoiture;
       this.marqueVoiture = marqueVoiture;
       this.modeleVoiture = modeleVoiture;
       this.categorieVoiture = categorieVoiture;
       this.couleurVoiture = couleurVoiture;
       this.carburantVoiture = carburantVoiture;
       this.boiteVitesseVoiture = boiteVitesseVoiture;
       this.climatisationVoiture = climatisationVoiture;
       this.nbrPortesVoiture = nbrPortesVoiture;
       this.nbrPlacesVoiture = nbrPlacesVoiture;
       this.typeVoiture = typeVoiture;
       this.etatVoiture = etatVoiture;
       this.anneeMiseService = anneeMiseService;
       this.type = type;
       this.image = image;
       this.prixParJour3jour = prixParJour3jour;
       this.prixParJour1semaine = prixParJour1semaine;
       this.entretients = entretients;
       this.factures = factures;
       this.contrats = contrats;
       this.reservations = reservations;
    }
   
    public Integer getIdVoiture() {
        return this.idVoiture;
    }
    
    public void setIdVoiture(Integer idVoiture) {
        this.idVoiture = idVoiture;
    }
    public Parc getParc() {
        return this.parc;
    }
    
    public void setParc(Parc parc) {
        this.parc = parc;
    }
    public String getImmatriculationVoiture() {
        return this.immatriculationVoiture;
    }
    
    public void setImmatriculationVoiture(String immatriculationVoiture) {
        this.immatriculationVoiture = immatriculationVoiture;
    }
    public String getMarqueVoiture() {
        return this.marqueVoiture;
    }
    
    public void setMarqueVoiture(String marqueVoiture) {
        this.marqueVoiture = marqueVoiture;
    }
    public String getModeleVoiture() {
        return this.modeleVoiture;
    }
    
    public void setModeleVoiture(String modeleVoiture) {
        this.modeleVoiture = modeleVoiture;
    }
    public String getCategorieVoiture() {
        return this.categorieVoiture;
    }
    
    public void setCategorieVoiture(String categorieVoiture) {
        this.categorieVoiture = categorieVoiture;
    }
    public String getCouleurVoiture() {
        return this.couleurVoiture;
    }
    
    public void setCouleurVoiture(String couleurVoiture) {
        this.couleurVoiture = couleurVoiture;
    }
    public String getCarburantVoiture() {
        return this.carburantVoiture;
    }
    
    public void setCarburantVoiture(String carburantVoiture) {
        this.carburantVoiture = carburantVoiture;
    }
    public String getBoiteVitesseVoiture() {
        return this.boiteVitesseVoiture;
    }
    
    public void setBoiteVitesseVoiture(String boiteVitesseVoiture) {
        this.boiteVitesseVoiture = boiteVitesseVoiture;
    }
    public String getClimatisationVoiture() {
        return this.climatisationVoiture;
    }
    
    public void setClimatisationVoiture(String climatisationVoiture) {
        this.climatisationVoiture = climatisationVoiture;
    }
    public int getNbrPortesVoiture() {
        return this.nbrPortesVoiture;
    }
    
    public void setNbrPortesVoiture(int nbrPortesVoiture) {
        this.nbrPortesVoiture = nbrPortesVoiture;
    }
    public int getNbrPlacesVoiture() {
        return this.nbrPlacesVoiture;
    }
    
    public void setNbrPlacesVoiture(int nbrPlacesVoiture) {
        this.nbrPlacesVoiture = nbrPlacesVoiture;
    }
    public String getTypeVoiture() {
        return this.typeVoiture;
    }
    
    public void setTypeVoiture(String typeVoiture) {
        this.typeVoiture = typeVoiture;
    }
    public String getEtatVoiture() {
        return this.etatVoiture;
    }
    
    public void setEtatVoiture(String etatVoiture) {
        this.etatVoiture = etatVoiture;
    }
    public String getAnneeMiseService() {
        return this.anneeMiseService;
    }
    
    public void setAnneeMiseService(String anneeMiseService) {
        this.anneeMiseService = anneeMiseService;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }
    public String getPrixParJour3jour() {
        return this.prixParJour3jour;
    }
    
    public void setPrixParJour3jour(String prixParJour3jour) {
        this.prixParJour3jour = prixParJour3jour;
    }
    public String getPrixParJour1semaine() {
        return this.prixParJour1semaine;
    }
    
    public void setPrixParJour1semaine(String prixParJour1semaine) {
        this.prixParJour1semaine = prixParJour1semaine;
    }
    public Set getEntretients() {
        return this.entretients;
    }
    
    public void setEntretients(Set entretients) {
        this.entretients = entretients;
    }
    public Set getFactures() {
        return this.factures;
    }
    
    public void setFactures(Set factures) {
        this.factures = factures;
    }
    public Set getContrats() {
        return this.contrats;
    }
    
    public void setContrats(Set contrats) {
        this.contrats = contrats;
    }
    public Set getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set reservations) {
        this.reservations = reservations;
    }




}


